[package]
name = "deno-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Note: `deno` has conflict over `curve25519-dalek` with `blockstack-core`
deno = "1.30"
