[workspace]
members = [
  "relay-server",
  "frost-test",
  "frost-signer",
  "frost-coordinator",
  "stacks-coordinator",
  "stacks-signer",
  "yarpc"]

[workspace.dependencies]
blockstack-core = { git = "https://github.com/stacks-network/stacks-blockchain/", branch = "3493-sbtc-peg-out-wire-format" }
clap = { version = "4.1.1", features = ["derive"] }
wtfrost = "3.0"
rusqlite = "0.28.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
thiserror = "1.0"
toml = "0.7.2"
rand_core = "0.6"
hashbrown = "0.13"
bincode = "1.3.3"
itertools = "^0.10.5"
sha3 = "0.10.6"
ureq = { version = "2.6", features = ["json"] }
rand = "0.8.5"
backoff = "0.4"
mockall = "0.11.3"
