name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.30.*
    - name: Build
      run: cargo build --verbose

  test:
    strategy:
      matrix:
        # can't run on `windows-latests`
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.30.*
    - uses: actions/checkout@v3
    # We need to cache JS script dependencies before running `cargo test`.
    # The `cargo test` command may spawn multiple `deno` processes.
    - name: Cache JS script dependencies
      run: deno cache ./stacks-js-rs/js/stacks.ts
    - name: Run tests
      run: cargo test --verbose

  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run fmt check
      run: cargo fmt --check
